name: Prod AZ - Deploy

on:
  push:
    tags:
      - 'v*.*.*'

env:
  AWS_EKS_CLUSTER_NAME: ${{ vars.AWS_EKS_CLUSTER_NAME_PROD_AZ }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID_PROD_AZ }}
  AWS_REGION: "us-west-2"
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME_PROD_AZ }}
  DD_AGENT_IMAGE: ${{ vars.DD_AGENT_IMAGE_PROD_AZ }}
  DOCKER_PLATFORM: "linux/amd64"
  DOCKER_REPO: "${{ vars.AWS_ACCOUNT_ID_PROD_AZ }}.dkr.ecr.${{ vars.AWS_REGION_PROD_AZ }}.amazonaws.com"
  DOCKER_REPO_DEV: "${{ vars.AWS_ACCOUNT_ID_DEV }}.dkr.ecr.${{ vars.AWS_REGION_DEV }}.amazonaws.com"
  ENVIRONMENT: prod-az
  HELM_REPO: ${{ vars.HELM_REPO }}
  HELM_VERSION: "1.1.2"
  SERVICE_NAME: ${{ vars.SERVICE_NAME }}
  BASE_DOMAIN: ${{ vars.BASE_DOMAIN_PROD_AZ }}

jobs:
  build_and_push_images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: write

    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: github-app-token
        with:
          app-id: ${{ vars.APP_ID }}
          owner: ${{ github.repository_owner }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
          ref: ${{ github.head_ref }}
          token: ${{ steps.github-app-token.outputs.token }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Prepare docker image tags
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-8)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "SERVICE_IMAGE_DEV=$DOCKER_REPO_DEV/$SERVICE_NAME:$IMAGE_TAG" >> $GITHUB_ENV
          echo "SERVICE_IMAGE=$DOCKER_REPO/$SERVICE_NAME:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Configure AWS Credentials for DEV
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}
          role-session-name: gh-actions
          aws-region: ${{ vars.AWS_REGION_DEV }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull images from DEV for promotion to Prod AZ
        run: |
          docker pull "$SERVICE_IMAGE_DEV"
          docker pull "$SERVICE_IMAGE_DEV"-migration

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: gh-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and Push the Docker images
        run: |
          docker tag "$SERVICE_IMAGE_DEV" "$SERVICE_IMAGE"
          docker push "$SERVICE_IMAGE"

          docker tag "$SERVICE_IMAGE_DEV"-migration "$SERVICE_IMAGE"-migration
          docker push "$SERVICE_IMAGE"-migration

      - name: "Update values for k8s files"
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: "__"
          tokenSuffix: "__"
          files: '["k8s/${{ env.ENVIRONMENT }}/**/*.yaml"]'

      - name: Configure Kubernetes client
        uses: silverlyra/setup-aws-eks@v0.1
        with:
          cluster: ${{ env.AWS_EKS_CLUSTER_NAME }}

      - name: "Helm Install for Service API"
        run: |
          helm repo add spartan https://x-access-token:${{ steps.github-app-token.outputs.token }}@${{ env.HELM_REPO }}
          helm upgrade --install --wait --timeout 600s \
            --namespace ${{ env.SERVICE_NAME }} \
            -f k8s/${{ env.ENVIRONMENT }}/values.yaml \
            --version ${{ env.HELM_VERSION }} \
            ${{ env.SERVICE_NAME }} spartan/spartan

      - name: "Extract Git info"
        run: |
          echo "GITHUB_AUTHOR=$(git log -1 --pretty=format:'%an <%ae>' | xargs)" >> $GITHUB_ENV
          echo "GITHUB_REVISION=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "GITHUB_REPO=$(git config --get remote.origin.url)" >> $GITHUB_ENV

          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          GITHUB_COMMITS=$(git --no-pager log --pretty=format:'%h (%an) %s' -n3 --no-color |  while read line || [ -n "$line" ]; do echo -n "- $line \\n"; done)
          echo "GITHUB_COMMITS<<$EOF" >> "$GITHUB_ENV"
          echo $GITHUB_COMMITS | sed "s/\"/'/g" >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"

      - name: Slack Notification
        id: slack
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":rocket: *${{ env.SERVICE_NAME }} - Deploy to PROD AstraZeneca*"
                  }
                },{
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Created by:* ${{ env.GITHUB_AUTHOR }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*API Docs:* https://${{ env.SERVICE_NAME }}.${{ env.BASE_DOMAIN }}/api/docs"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "```${{ env.GITHUB_COMMITS }}```"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View changes"
                      },
                      "style": "primary",
                      "url": "${{ env.GITHUB_REPO }}/commit/${{ env.GITHUB_REVISION}}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Run"
                      },
                      "style": "primary",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
